camdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staticpages.urls')),
    path('semov/', include('semov.urls')),
    #path('avaliacoes/', include('avaliacoes.urls')),
    path('estagios/', include('estagios.urls')),
    path('usuarios/', include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

estagios/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.EstagioListView.as_view(), name='estagios'),
]

semov/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='semov_index'),
    path('schedule', views.schedule, name='semov_schedule'),
]

estagios/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
    nome = models.CharField(max_length=20)
    def __str__(self):
        return self.nome

class Vaga(models.Model):
    titulo = models.CharField(max_length=100, verbose_name='Título')
    empresa = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, verbose_name='Descrição da vaga')
    requisitos = models.TextField(blank=True)
    inscricao = models.CharField(max_length=100, verbose_name='Inscrição')
    tags = models.ManyToManyField(Tag, blank=True)
    def __str__(self):
        return self.titulo

estagios/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from .models import Vaga
from django.views.generic import ListView
# Create your views here.
class EstagioListView(ListView):
    model = Vaga
    template_name = 'estagios/estagios.html'
    def get_queryset(self):
        qs = self.request.GET.get('tag')
        if qs:
            qs = Vaga.objects.filter(tags__nome__icontains=qs)
        else:
            qs = Vaga.objects.all()
        return qs

estagios/templates/estagios/estagios.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Estágios
{% endblock %}
{% block nav %}
<ul>
    <li><a href="#"><h1>Estágios</h1></a></li>
</ul>
{% endblock %}

{% block content %}
<div class="row">    
    {% for vaga in vaga_list %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ vaga.titulo }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Empresa: {{ vaga.empresa }}</h6>
                <p class="card-text">{{ vaga.descricao }}</p>
                <strong>Inscrição: </strong> {{ vaga.inscricao }}
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      {% for tag in vaga.tags.all %}
                      <a href="#" class="btn btn-sm btn-outline-secondary"><i class="icofont-tag"></i>{{ tag.nome }}</a>
                      {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}