camdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staticpages.urls')),
    path('semov/', include('semov.urls')),
    #path('avaliacoes/', include('avaliacoes.urls')),
    path('estagios/', include('estagios.urls')),
    path('usuarios/', include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

semov/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='semov_index'),
    path('schedule', views.schedule, name='semov_schedule'),
]

staticpages/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('historia', views.historia, name='historia'),
    path('carometro', views.MembrosListView.as_view(), name='carometro'),
    path('diretorias', views.DiretoriasListView.as_view(), name='diretorias'),
    path('faq', views.FaqListView.as_view(), name='faq'),
    path('contato', views.ContatoListView.as_view(), name='contato'),
    #path('semov_index', views.semov_index, name='semov_index'),
]

staticpages/models.py
from django.db import models

# Create your models here.
class Membro(models.Model):
    nome = models.CharField(max_length=100)
    imagem = models.ImageField(upload_to='membros')
    cargo = models.CharField(max_length=100)
    ordem = models.IntegerField()
    facebook = models.CharField(max_length=100)
    instagram = models.CharField(max_length=100)
    linkedin = models.CharField(max_length=100)
    def __str__(self):
        return self.nome

class Diretoria(models.Model):
    nome = models.CharField(max_length=100)
    imagem = models.ImageField(upload_to='diretorias')
    ordem = models.IntegerField()
    descricao = models.TextField(max_length=511)
    def __str__(self):
        return self.nome

class Faq(models.Model):
    pergunta = models.CharField(max_length=100)
    resposta = models.TextField(max_length=511)
    ordem = models.IntegerField()
    def __str__(self):
        return self.pergunta

class Contato(models.Model):
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=100)
    whatsapp = models.URLField(max_length=100)
    ordem = models.IntegerField()
    def __str__(self):
        return self.nome

class Slide(models.Model):
    titulo = models.CharField(max_length=100)
    conteudo = models.TextField(max_length=511)
    imagem = models.ImageField(upload_to='slides')
    link = models.URLField(max_length=100)
    ordem = models.IntegerField()
    def __str__(self):
        return self.titulo

staticpages/forms.py
from django import forms
from .models import Membro, Diretoria, Faq, Contato

class MembroForm(forms.ModelForm):
    class Meta:
        model = Membro
        fields = ['nome', 'imagem', 'cargo', 'ordem', 'facebook', 'instagram', 'linkedin']
        widgets = {
            'imagem': forms.ClearableFileInput(),
        }

    imagem = forms.FileField(widget=forms.ClearableFileInput())

class DiretoriaForm(forms.ModelForm):
    class Meta:
        model = Diretoria
        fields = ['nome', 'imagem', 'ordem', 'descricao']
        widgets = {
            'imagem': forms.ClearableFileInput(),
        }

    imagem = forms.FileField(widget=forms.ClearableFileInput())

class FaqForm(forms.ModelForm):
    class Meta:
        model = Faq
        fields = ['pergunta', 'resposta', 'ordem']

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ['nome', 'telefone', 'whatsapp', 'ordem']

staticpages/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from staticpages.models import Membro, Diretoria, Faq, Contato, Slide
from .forms import MembroForm, DiretoriaForm, FaqForm, ContatoForm
# Create your views here.

def index(request):
    slides = Slide.objects.order_by('ordem')
    context = {'slide_list': slides}
    return render(request, 'staticpages/index.html', context)

def historia(request):
    return render(request, 'staticpages/historia.html')

class MembrosListView(ListView):
    model = Membro
    template_name = 'staticpages/carometro.html'
    def get_queryset(self):
        return Membro.objects.order_by('ordem')

class DiretoriasListView(ListView):
    model = Diretoria
    template_name = 'staticpages/diretorias.html'
    def get_queryset(self):
        return Diretoria.objects.order_by('ordem')

class FaqListView(ListView):
    model = Faq
    template_name = 'staticpages/faq.html'
    def get_queryset(self):
        return Faq.objects.order_by('ordem')

def semov_index(request):
    return render(request, 'staticpages/semov_index.html')
class ContatoListView(ListView):
    model = Contato
    template_name = 'staticpages/contato.html'
    def get_queryset(self):
        return Contato.objects.order_by('ordem')

staticpages/templates/staticpages/carometro.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Carômetro{% endblock %}
{% block nav %}
{% include 'nav_index.html' %}
{% endblock %}
{% block content %}
    <main id="main">

    <!-- ======= Our Team Section ======= -->
    <section id="team" class="team section-bg">
      <div class="container">

        <div class="section-title" >
          <h2> <strong>Gestão CAMadas 2023</strong></h2>
          <p>
            </p>
        </div>
        <div class="row">
        {% for membro in membro_list %}
          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="1">
              <div class="member-img">
                <img src="{{ membro.imagem.url }}" class="img-fluid" alt="">
                <div class="social">
                    <a href="{{ membro.facebook }}"><i class="icofont-facebook"></i></a>
                    <a href="{{ membro.instagram }}"><i class="icofont-instagram"></i></a>
                    <a href="{{ membro.linkedin }}"><i class="icofont-linkedin"></i></a>  
                </div>
              </div>
              <div class="member-info">
                <h4>{{ membro.nome }}</h4>
                <span>{{ membro.cargo }}</span>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
    </main>
{% endblock %}

staticpages/templates/staticpages/contato.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Contato{% endblock %}
{% block nav %}
{% include 'nav_index.html' %}
{% endblock %}
{% block content %}
<main id="main" class="section3">
    <!-- ======= Contact Section ======= -->
    <div class="map-section">
      <iframe style="border:0; width: 100%; height: 350px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.42959070642!2d-46.73114398271042!3d-23.55300986966435!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce5617f611fdeb%3A0x3417ccf5fc732a4c!2sCAM%20-%20Centro%20Acad%C3%AAmico%20Mec%C3%A2nica%20e%20Mecatr%C3%B4nica!5e0!3m2!1spt-BR!2sbr!4v1600636471064!5m2!1spt-BR!2sbr" frameborder="0" allowfullscreen></iframe>
    </div>

    <section id="contact" class="contact">
      <div class="container">

        <div class="row justify-content-center" data-aos="fade-up">

          <div class="col-lg-10">

            <div class="info-wrap">
              <div class="row">
                <div class="col-lg-4 info">
                  <i class="icofont-google-map"></i>
                  <h4> Localização: </h4>
                  <p>
                    Av. Prof. Mello Moraes 2231,
                    <br>São Paulo, SP 05508-030
                  </p>
                </div>

                <div class="col-lg-4 info mt-4 mt-lg-0">
                  <i class="icofont-envelope"></i>
                  <h4>Email:</h4>
                  <p>academico.cam@gmail.com</p>
                </div>

                <div class="col-lg-4 info mt-4 mt-lg-0">
                  <i class="icofont-phone"></i>
                  <h4>Telefone:</h4>
                    <p>
                      {% for contato in contato_list %}
                      <a href="{{ contato.whatsapp }}">{{contato.nome}}: {{ contato.telefone }}</a>
                      <br>
                      {% endfor %}
                    </p>      
                </div>
              </div>
            </div>

          </div>

        </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->
{% endblock %}

staticpages/templates/staticpages/diretorias.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Diretorias{% endblock %}
{% block nav %}
{% include 'nav_index.html' %}
{% endblock %}
{% block content %}
<main id="main">
    <!-- ======= Diretoria Section ======= -->
    <!-- ======= Fotos 160x160 px  ======= -->
    <section id="team" class="team section-bg" style="padding-bottom: 30px;">
      <div class="container">
        <div class="section-title" data-aos="fade-up">
          <h2><strong>Diretorias</strong></h2>
          <p>Com a finalidade de melhorar a administração do nosso querido CAM, a gestão é dividida em Diretorias. Cada uma delas é responsável por um ou mais processos e tarefas dentro da gestão. Conheça cada uma delas abaixo!</p>
        </div>
      </div>
    </section>
    <section id="diretoria" class="diretoria section-bg" style="padding-top: 0px;">
      <div class="container">
        <div class="row">
        {% for diretoria in diretoria_list %}
          <div class="col-lg-6" data-aos="fade-up">
            <div class="diretoria-item mt-4">
              <img src="{{ diretoria.imagem.url }}" class="diretoria-img" alt="imagem representando a {{ diretoria.nome }}">
              <h3>{{ diretoria.nome }}</h3>
            {{ diretoria.descricao }}
          </div>
          </div>
        {% endfor %}
      </div>
    </section><!-- End diretoria Section -->

  </main><!-- End #main -->
{% endblock %}

staticpages/templates/staticpages/faq.html
{% extends 'base.html' %}
{% load static %}
{% block title %} FAQ{% endblock %}
{% block nav %}
{% include 'nav_index.html' %}
{% endblock %}
{% block content %}
  <main id="main">
    <!-- ======= Frequently Asked Questions Section ======= -->
    <section id="faq" class="faq section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Perguntas Frequentes</h2>
        </div>

        <div class="faq-list">
          <ul>
            {%for faq in faq_list %}
            <li data-aos="fade-up">
              <i class="bx bx-help-circle icon-help"></i> <a data-toggle="collapse" class="collapsed" href="#faq-list-{{ faq.id }}"> {{ faq.pergunta }} <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-{{ faq.id }}" class="collapse" data-parent=".faq-list">
                <p>
                  {{ faq.resposta|safe }}
                </p>
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>

      </div>
    </section><!-- End Frequently Asked Questions Section -->

  </main><!-- End #main -->

  {% endblock content %}

staticpages/templates/staticpages/historia.html
{% extends 'base.html' %}
{% load static %}
{% block title %} História{% endblock %}
{% block nav %}
{% include 'nav_index.html' %}
{% endblock %}
{% block content %}
<section id="about-us" class="space section-bg section2">
    <div class="row middle-xs center-xs align-items-center">

        <div class="col-md-6" data-aos="fade-right">
          <h2>Fundação</h2>
          <p>
            O CAM foi fundado oficialmente no dia 28 de Novembro de 1990,
             porém sua história vem de mais longe do que isso.
             Desde o início da Escola Politécnica, existiam entidades acadêmicas, 
             porém isso não era comum a todos os cursos, até que na década de 50 
             um dos primeiros centros acadêmicos foi fundado, a Associação de Engenharia Mecânica (AEM), 
             esta associação perdurou por bastante tempo até que na década de 60, eles se juntaram com o 
             Centro de Engenharia de Produção (CAEP), formando assim o Centro de Produção Mecânica (CPM). 
             Essa parceria durou até 1987 onde ocorreu a separação do CPM, onde aí sim surgiu o CAM, 
             o Centro Acadêmico Mecânica, sendo que foi realmente registrado em 1990.
          </p>
        </div>
        <div class="col-md-5" data-aos="fade-left">
          <img src="{% static '/img/WhatsApp Image 2021-04-03 at 16.18.30.jpeg' %}" height="300vh" class="img-hist"/>
        </div>

      </div>

    </div>
  </section><!-- End About Us Section -->

{% endblock %}